version: '3.8'
services:

  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE: appdb
      - MYSQL_USER: siva
      - MYSQL_PASSWORD: secret
      - MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"


